from asyncio.windows_events import NULL
from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from janela_cadastro import *


class JanelaMain(object):    
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(566, 364)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cabecalho = QtWidgets.QFrame(self.centralwidget)
        self.cabecalho.setMaximumSize(QtCore.QSize(16777215, 45))
        self.cabecalho.setAutoFillBackground(False)
        self.cabecalho.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.cabecalho.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.cabecalho.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cabecalho.setObjectName("cabecalho")
        self.verticalLayout.addWidget(self.cabecalho)
        self.fundo_main = QtWidgets.QFrame(self.centralwidget)
        self.fundo_main.setStyleSheet("background-color: rgb(214, 214, 106);")
        self.fundo_main.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.fundo_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fundo_main.setObjectName("fundo_main")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.fundo_main)
        self.horizontalLayout.setContentsMargins(100, 50, 100, 50)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fundo_interacao = QtWidgets.QFrame(self.fundo_main)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.fundo_interacao.setFont(font)
        self.fundo_interacao.setStyleSheet("background-color: rgb(186, 186, 186);")
        self.fundo_interacao.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.fundo_interacao.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fundo_interacao.setObjectName("fundo_interacao")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.fundo_interacao)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.fundo_interacao)
        self.label.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.fundo_interacao)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.label_2 = QtWidgets.QLabel(self.fundo_interacao)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.fundo_interacao)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_2.addWidget(self.lineEdit_2)
        self.pushButton = QtWidgets.QPushButton(self.fundo_interacao)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.fundo_interacao)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.fundo_interacao)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_2.addWidget(self.pushButton_3)
        self.horizontalLayout.addWidget(self.fundo_interacao)
        self.verticalLayout.addWidget(self.fundo_main)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Login"))
        self.label.setText(_translate("MainWindow", "Usuário"))
        self.label_2.setText(_translate("MainWindow", "Senha"))
        self.pushButton.setText(_translate("MainWindow", "Efeturar login"))
        self.pushButton_2.setText(_translate("MainWindow", "Esqueci a senha"))
        self.pushButton_3.setText(_translate("MainWindow", "Cadastre-se clicando aqui"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = JanelaMain()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
